// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AuthsApplicationJSON struct {
	// The email of the user
	Email string `json:"email"`
	// The password of the user
	Password string `json:"password"`
}

type AuthsResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
