// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EnrichCompanyRequest struct {
	// ID of the company
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type EnrichCompanyResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
