// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EnrichPersonRequest struct {
	// LinkedIn ID of the person
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type EnrichPersonResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
