// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Account struct {
	// List of the users in the account
	AccountUsers []string
	// Timestamp of the account creation date
	CreatedAt string
	// The id of the account
	ID float64
	// The name of the account
	Name string
	// The id of the account owner
	OwnerID float64
	// If the account is personal or belonging to another account
	Personal bool
	// Timestamp of the last account update date
	UpdatedAt string
}
