// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Company - returns the company
type Company struct {
	// The company's description
	About string
	// Affiliated companies to the company
	Affiliated []string
	// The size of the company
	CompanySize string
	// The country's country code
	CountryCode string
	// A sample of the company's employees. See the employees endpoint for the full list.
	Employees []string
	// The number of company employees on LinkedIn
	EmployeesInLinkedin float64
	// The number of company followers on LinkedIn
	Followers float64
	// The year the company was founded
	Founded float64
	// The funding status of the company
	Funding string
	// The country's headquarters
	Headquarters string
	// The key for looking up the company
	ID float64
	// The company's industries
	Industries string
	// The company's investors
	Investors string
	// Sample of company's Jobs. See the jobs endpoint for the full list.
	Jobs []string
	// The company's LinkedIn ID
	Lid string
	// The company's locations
	Locations []string
	// URL to the company's logo
	Logo string
	// The company's name
	Name string
	// The type of organization
	OrganizationType string
	// The comapny's headquarters region
	Region string
	// Similar companies to this company
	Similar []string
	// The company's slogan
	Slogan string
	// The company's specialities
	Specialities string
	// The company's sphere of products
	Sphere string
	// The type of company (public, private, etc.)
	Type string
	// The company's linkedIn URL
	URL string
	// The company's website
	Website string
}
