// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Person - returns the person
type Person struct {
	// The birth date of the person
	BirthDate string
	// The birth year of the person
	BirthYear float64
	// The certifications of the person
	Certifications []string
	// The educational history of the person
	Education []string
	// The personal and work emails of the person
	Emails []string
	// The works experience of the person
	Experience []string
	// The Facebook ID of the person
	FacebookID string
	// The Facebook URL of the person
	FacebookURL string
	// The Facebook username of the person
	FacebookUsername string
	// The first name of the person
	FirstName string
	// The full name of the person
	FullName string
	// The gender of the person
	Gender string
	// The Github URL of the person
	GithubURL string
	// The Github username of the person
	GithubUsername string
	// The key for looking up the company
	ID float64
	// The industry of the person
	Industry string
	// The inferred salary band for the person
	InferredSalary string
	// The inferred years of experience for the person
	InferredYearsExperience float64
	// The interests of the person
	Interests []string
	// The current job company Facebook URL
	JobCompanyFacebookURL string
	// The current job company founded year
	JobCompanyFounded string
	// The current job company ID
	JobCompanyID string
	// The current job company industry
	JobCompanyIndustry string
	// The current job company id on LinkedIn
	JobCompanyLinkedinID string
	// The current job company LinkedIn URL
	JobCompanyLinkedinURL string
	// The current job company location street adress second line
	JobCompanyLocationAddressLine2 string
	// The current job company location continent
	JobCompanyLocationContinent string
	// The current job company location country
	JobCompanyLocationCountry string
	// The current job company location geo coordinates
	JobCompanyLocationGeo string
	// The current job company location city
	JobCompanyLocationLocality string
	// The current job company location metro
	JobCompanyLocationMetro string
	// The current job company location name
	JobCompanyLocationName string
	// The current job company location postal code
	JobCompanyLocationPostalCode string
	// The current job company location region
	JobCompanyLocationRegion string
	// The current job company location street address
	JobCompanyLocationStreetAddress string
	// The current job company name
	JobCompanyName string
	// The current job company size
	JobCompanySize string
	// The current job company Twitter URL
	JobCompanyTwitterURL string
	// The current job company website
	JobCompanyWebsite string
	// The last update date for the job
	JobLastUpdated string
	// The start date for the current job
	JobStartDate string
	// The summary for the current job
	JobSummary string
	// The current job title of the person
	JobTitle string
	// The current job title levels
	JobTitleLevels []string
	// The current job title role of the person
	JobTitleRole string
	// The current job title sub-role of the person
	JobTitleSubRole string
	// The languages of the person
	Languages []string
	// The last name of the person
	LastName string
	// The number of LinkedIn connections for the person
	LinkedinConnections float64
	// The linkedIn ID of the person
	LinkedinID float64
	// The linkedIn URL of the person
	LinkedinURL string
	// The linkedIn user name of the person
	LinkedinUsername string
	// The current location street address second line for the person
	LocationAddressLineTwo string
	// The current location continent for the person
	LocationContinent string
	// The current location country for the person
	LocationCountry string
	// The current location geo coordinates for the person
	LocationGeo []string
	// The current location last updated date for the person
	LocationLastUpdated string
	// The current location city for the person
	LocationLocality string
	// The current location metro for the person
	LocationMetro string
	// The current location name for the person
	LocationName string
	// The current location postal code for the person
	LocationPostalCode string
	// The current location region for the person
	LocationRegion string
	// The current location street address for the person
	LocationStreetAddress string
	// The middle initial of the person
	MiddleInitial string
	// The middle name of the person
	MiddleName string
	// The mobile phone of the person
	MobilePhone string
	// The phone numbers of the person
	PhoneNumbers []string
	// The social profiles of the person
	Profiles []string
	// The skills of the person
	Skills []string
	// The street addresses of the person
	StreetAddresses []string
	// The self-summary of the person's work experience
	Summary string
	// The Twitter URL of the person
	TwitterURL string
	// The Twitter username of the person
	TwitterUsername string
	// The work email of the person
	WorkEmail string
}
